### PR TITLE
Update action versions

### LINKED ISSUE #14: Update Github Action "Wheel" to use latest actions/upload-artifact
Action [Wheel](https://github.com/WildMeOrg/scoutbot/actions/workflows/python-publish.yml) fails due to use of deprecated v2 of `actions/upload-artifact`.  
See [latest action run](https://github.com/WildMeOrg/scoutbot/actions/runs/11615189758) for failure and [deprecation notice](https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/) for info on upgrading.

### PR DESCRIPTION
**Pull request by vkirkl**
Quite a few actions were outdated and in many cases deprecated, causing failures.  This should get them updated to latest versions.  
Python versions in some of the actions were also very old and some were inconsistent.  This should move them all to the latest stable version.

See [Issue 14](https://github.com/WildMeOrg/scoutbot/issues/14) for more discussion.  Resolves #14.

### CODE REVIEW

**Comment by vkirkl** [comment]
Note that the [Codecov GitHub Action(https://github.com/codecov/codecov-action) should be reviewed for upgrade as well.

**Comment by vkirkl** [comment]
This also makes PR #12 from dependabot redundant.

**Comment by vkirkl** [comment]
> Note that the [Codecov GitHub Action](https://github.com/codecov/codecov-action) in testing.yaml should be reviewed for upgrade as well.

codecov-action updated to v4.

**Comment by vkirkl** [comment]
@LashaO and @TanyaStere42  ... if someone else is a better choice for review, please pass this along.

**Comment by vkirkl** [comment]
PR #19 should proceed this one.

**Comment by LashaO** [comment]
Awesome. Ready to merge this once tests complete.

**Review by TanyaStere42 — APPROVED** [review]
passed tests, in the right order, lasha approved verbally, getting this in :D

**Comment by LashaO** [comment]
Thank you!

**Pull request merged**
